Update Spanish translations
jossemarGT/k8s-dashboard pull request #1
Opened 2023-10-31 14:27 UTC by jossemarGT

Hola equipo, esta es mi primer iteración revisando las cadenas traducidas al español en el K8s Dashboard.

Los cambios en este PR pueden ser agrupados de la siguiente manera:

- **Correcciones gramaticales**. Como por ejemplo uso de tíldes o artículos redudantes.
- **Actualización de cadenas**. Algunos cadenas en Español ya no seguían el patrón de la cadena original, esto sucede únicamente en donde se tienen tags `<></>` entre cadenas.
- **Ajuste de espacios vacíos**.  Esto era necesario dado que la cadena original tambien contiene dichos espacios vacíos al inicio o al final y sin ellos el web UI podría renderizarse incorrectamente.

Hay varios términos que tienen discrepancias _que no actualicé en este PR_ y necesito discutir con ustedes como abordarlos. Listaré algunos para ejemplificar:

- Términos cómo `Service` /  `Servicio` ó `Ingress` / `Ingreso` se intercambian en las cadenas traducidas en Español.
- Similar a lo anterior, el término `Secret` tiene incidencias tanto con su traducción como `secreto` o bien `secret` sin la primer letra en mayúscula.
- Existen traducciones de términos en Inglés que no se suelen traducir como Host, en lugar de anfitrión.
- Existen términos en Inglés que pueden ser traducidos como Registros, en lugar de Logs.

En caso quieran hacer fork de este repositorio y agregar sus contribuciones por favor tener lo siguiente en mente:

- Hacer fork **completo**, dado que sin ello no tendrán los git tags disponibles y estos son vitales para ejecutar las herramientas/scripts de desarrollo.
- En caso deseen refrescar las cadenas en los ficheros `.xlf` deben tener todas las herramientas de desarrollo. Para ello necesitan seguir estos documentos:  [Getting started](https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md#preparation), [Internationalization](https://github.com/kubernetes/dashboard/blob/master/docs/developer/internationalization.md)
- Para hacer push de los cambios _necesitan_ ya sea instalar las herramientas de desarrollo (ej: NodeJS) o agregar la bandera `--no-verify` al final del `git push`.

2023-11-14 19:32 UTC, ramrodo commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> El valor de la etiqueta no dee exceder 253 caracteres. </target>
```suggestion
        <target state="new"> El valor de la etiqueta no debe exceder 253 caracteres. </target>
```

2023-11-14 19:34 UTC, ramrodo requested changes
Great!

Just one suggestion :)

2023-11-15 19:18 UTC, electrocucaracha requested changes

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target>Un Secret con el nombre especificado será añadido al clúster en el espacio de nombre.</target>
```suggestion
        <target>Un Secret con el nombre especificado será añadido al clúster en el Namespace.</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target>Máx. de réplicas</target>
```suggestion
        <target>Máx. número de réplicas</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new">Puedes <x id="START_LINK" ctype="x-a" equiv-text="&lt;a&gt;"/>desplegar una aplicación contenerizada<x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/>, selecciona ot
```suggestion
        <target state="new">Puedes <x id="START_LINK" ctype="x-a" equiv-text="&lt;a&gt;"/>desplegar una aplicación contenerizada<x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/>, selecciona otro Namespace o <x id="START_LINK_1" ctype="x-a" equiv-text="&lt;a&gt;"/>revisa la documentación del Dashboard <x id="START_TAG_MAT-ICON" ctype="x-mat-icon" equiv-text="&lt;mat-icon&gt;"/>open_in_new<x id="CLOSE_TAG_MAT-ICON" ctype="x-mat-icon" equiv-text="&lt;/mat-icon&gt;"/> <x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/> para aprender más.</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> El puerto debe ser superior a 0. </target>
```suggestion
        <target state="new"> El puerto debe ser mayor a 0. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new">El nombre debe tener hasta <x id="INTERPOLATION" equiv-text="{{namespaceMaxLength}}"/> caracteres.</target>
```suggestion
        <target state="new">El nombre debe tener hasta <x id="INTERPOLATION" equiv-text="{{namespaceMaxLength}}"/> caractéres.</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new">El nombre debe tener hasta <x id="INTERPOLATION" equiv-text="{{secretNameMaxLength}}"/> caracteres.</target>
```suggestion
        <target state="new">El nombre debe tener hasta <x id="INTERPOLATION" equiv-text="{{secretNameMaxLength}}"/> caractéres.</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target>Mín. réplicas</target>
```suggestion
        <target>Mín. número de réplicas</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> el requisito de CPU debe ser un número válido. </target>
```suggestion
        <target state="new"> El requisito de CPU debe ser un número válido. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Un Deployment o un service ya existe con este nombre dentro del espacio de nombre. </target>
```suggestion
        <target state="new"> Un Deployment o Service con este nombre ya existe dentro del Namespace. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Crear un nuevo espacio de nombre... </target>
```suggestion
        <target state="new"> Crear un nuevo Namespace... </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Ingresa un contenido YAML O JSON especificando los recursos para crear en el espacio de nombres seleccionado. </target>
```suggestion
        <target state="new"> Ingresa un contenido YAML o JSON especificando los recursos para crear en el Namespace seleccionado. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Ingresa un contenido YAML O JSON especificando los recursos para crear el espacio de nombre especificado en el fichero. </target>
```suggestion
        <target state="new"> Ingresa un contenido YAML o JSON especificando los recursos para crear el Namespace especificado en el fichero. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Puedes <x id="START_LINK" ctype="x-a" equiv-text="&lt;a&gt;"/>desplegar una aplicación contenerizada<x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/>, selecciona o
```suggestion
        <target state="new"> Puedes <x id="START_LINK" ctype="x-a" equiv-text="&lt;a&gt;"/>desplegar una aplicación contenerizada<x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/>, selecciona otro Namespace o <x id="START_LINK_1" ctype="x-a" equiv-text="&lt;a&gt;"/>revisa la documentación del Dashboard <x id="START_TAG_MAT-ICON" ctype="x-mat-icon" equiv-text="&lt;mat-icon&gt;"/>open_in_new<x id="CLOSE_TAG_MAT-ICON" ctype="x-mat-icon" equiv-text="&lt;/mat-icon&gt;"/> <x id="CLOSE_LINK" ctype="x-a" equiv-text="&lt;/a&gt;"/> para aprender más. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target>El nuevo Secret será añadido al clúster</target>
```suggestion
        <target>El Secret nuevo será añadido al clúster</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target>Por defecto, tus contenedores ejecutan el comando entrypoint defecto de la imagen seleccionada. Puedes usar las opciones de comando para sobreescribirlas.</target>
```suggestion
        <target>De forma predeterminada, tus contenedores ejecutan el comando entrypoint por defecto de la imagen seleccionada. Puedes usar las opciones de comando para sobreescribirlas.</target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new">Anfitrión </target>
Me parece que si este elemento se traduce puede confundir al usuario
```suggestion
        <target state="new">Host </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Establecer un número alto de pods puede causar problemas de desempeño del clúster y la interfaz gráfica del Dashboard. </target>
```suggestion
        <target state="new"> Establecer un número elevado de Pods puede causar problemas de desempeño del clúster y la interfaz gráfica del Dashboard. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new">Espacio de nombre: </target>
```suggestion
        <target state="new">Namespace: </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> El nombre de la clave de la etiqueta no debe exceder 63 caracteres. </target>
```suggestion
        <target state="new"> El nombre de la clave de la etiqueta no debe exceder 63 caractéres. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> El prefijo no debe exceder 253 caracteres. </target>
```suggestion
        <target state="new"> El prefijo no debe exceder 253 caractéres. </target>
```

2023-11-15 19:18 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> Selecciona un fichero YAML o JSON especificando los recursos a desplegar en el espacio de nombre seleccionado. </target>
```suggestion
        <target state="new"> Selecciona un fichero YAML o JSON especificando los recursos a desplegar en el Namespace seleccionado. </target>
```

2023-11-20 17:14 UTC, jossemarGT commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> El nombre de la clave de la etiqueta no debe exceder 63 caracteres. </target>
Te soy sincero, yo tuve que buscar en internet el uso de la tilde en esta palabra. De lo cual encontré que `carácter` aplica en un contexto diferente y parece que `caractéres` no existe.

2023-11-20 18:43 UTC, electrocucaracha commented on modules/web/i18n/es/messages.es.xlf
> +        <target state="new"> El nombre de la clave de la etiqueta no debe exceder 63 caracteres. </target>
Ok, dejémoslo como está (sin tilde) y si encontramos evidencia contundente actualizamos este y otros documentos.

2023-11-21 15:46 UTC, jossemarGT commented on modules/web/i18n/es/messages.es.xlf
> +        <target>Un Secret con el nombre especificado será añadido al clúster en el espacio de nombre.</target>
Como conversamos ayer (2023/11/20) en Slack de la CNCF `#glossary-localization-spanish`, pospondré el utilizar términos del Kubernetes API como nombres propios en un PR aparte. 

Por lo tanto no podré aplicar tus sugerencias de utilizar `Namespace`.

2023-11-28 16:58 UTC, electrocucaracha approved these changes

2023-12-04 17:31 UTC, jossemarGT commented
Gracias por su apoyo @ramrodo @electrocucaracha , este cambio ya fue hecho merge en upstream https://github.com/kubernetes/dashboard/pull/8523 🥳 

Procederé a cerrar este PR sin hacer merge para evitar conflictos de git.

2023-12-04 17:31 UTC, closed without merging